fallback_comments = [
    "Jugaste con iniciativa al optar por 6.Bg5, pero aceptaste un peón en la jugada 13 sin evaluar la actividad rival. Recuerda que en la Siciliana, el dinamismo pesa más que el material. En lugar de buscar consolidar, abriste líneas prematuramente. El error táctico final fue consecuencia de una mala coordinación previa. Consejo: estudia sacrificios temáticos en la Najdorf y trabaja en mantener el equilibrio entre agresión y solidez. Una partida instructiva para aprender a reconocer la compensación dinámica del oponente",
    "Tu apertura fue correcta, pero luego te faltó plan. Repetiste movimientos sin avanzar y permitiste que las negras rompieran con ...c5. En la Española cerrada, la clave está en maniobrar hacia el flanco rey o controlar d5, no en simplemente esperar. El final fue técnicamente complicado y te faltó precisión para sostenerlo. Consejo: estudia planes estratégicos típicos en esta apertura y cómo coordinar tus torres en columnas abiertas. A veces, las tablas no reflejan oportunidades perdidas",
    "Tu ataque fue valiente, pero prematuro. Avanzar h5 sin desarrollo completo te dejó vulnerable. Las negras sacrificaron calidad y tomaron control de las casillas oscuras. A partir de ahí, perdiste coordinación y erraste en el cálculo. Consejo: en la Francesa, es vital reforzar el centro antes de lanzarse al flanco. También, cuida el equilibrio entre ataque y defensa: no dejes piezas fuera de juego. Aprende de esta partida cómo castiga una defensa sólida los ataques sin fundamento.",
    "Mantuviste el equilibrio durante toda la partida, mostrando buena comprensión posicional. Sin embargo, perdiste la oportunidad de luchar por más con ideas como ...e5. En posiciones simétricas, hay que encontrar momentos sutiles para desequilibrar. El final fue bien manejado, aunque sin ambición. Consejo: trabaja en detectar cuándo puedes cambiar el ritmo y jugar más activamente sin arriesgar demasiado. A veces, pequeñas iniciativas generan presión psicológica decisiva",
    "Iniciaste bien con f3 y e4, pero descuidaste el desarrollo. El ataque negro fue temático y no supiste responder. El sacrificio en h3 te tomó desprevenido y no lograste contrajuego real en el flanco dama. Consejo: antes de avanzar, asegúrate de tener piezas listas y rey seguro. Estudia cómo las blancas pueden evitar ser sobrepasadas en esta variante. En aperturas tan agresivas, el cálculo y el ritmo lo son todo"
]

fallback_ratings = [
    1373, 1733, 1280, 970, 1517
]